version: "3.8"

networks:
    grafana:

volumes:
    my-db:

services:
    cypress:
        image: cypress/base
        container_name: cypress

    # cypressBrowser:
    #     image: cypress/browserscypress/base
    #     container_name: cypressBrowser
    newman:
        image: postman/newman_alpine33
        container_name: newman
    jmeterTest: 
        image: justb4/jmeter
        container_name: jmeter

    prometheus:
        image: prom/prometheus:v2.16.0
        volumes:
        - ./prometheus/:/etc/prometheus/
        command:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        ports:
        - 9090:9090
        networks:
        - grafana 

    grafana:
        image: grafana/grafana:7.0.4
        ports:
        - 3005:3005
        networks:
        - grafana
    db:
        image: mysql:5.7
        restart: always
        environment:
        MYSQL_DATABASE: 'db'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'user'
        # You can use whatever password you like
        MYSQL_PASSWORD: 'password'
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'password'
        ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'
        expose:
        # Opens port 3306 on the container
        - '3306'
        # Where our data will be persisted
        volumes:
        - my-db:/var/lib/mysql
        